# Generated by Django 5.1 on 2024-08-09 09:04

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(null=True, upload_to=posts.models.image_path),
        ),
    ]
