# Generated by Django 5.1 on 2024-08-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="creation_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
